# Apply mold to all Linux targets EXCEPT MIPS
# MIPS is excluded because mold does not support it.
[target.'cfg(all(target_os = "linux", not(any(target_arch = "mips", target_arch = "mips64"))))']
rustflags = ["-C", "link-arg=-fuse-ld=mold"]